
services:
  query_translator:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    build:
      context: ./query_translator 
    volumes:
      - ./query_translator:/app 
    ports:
      - "5000:5000" 
    environment:
      - ENV_VAR=value 
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend 
    volumes:
      - ./backend:/app 
    ports:
      - "5001:5000" 
    environment:
      - QUERY_TRANSLATOR_URL=http://query_translator:5000
      - MYSQL_HOST=mysql 
      - MYSQL_PORT=3306 
      - MYSQL_USER=root 
      - MYSQL_PASSWORD=root
      - MYSQL_DB=database 
    networks:
      - mynetwork
    depends_on:
      - mysql
      - query_translator

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
